apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: default
  destination:
    name: k8s-wl-snd-use1-default
    namespace: demo-problem
  ignoreDifferences:
  - group: '*'
    kind: '*'
    managedFieldsManagers:
    - rollouts-controller
  source:
    path: yhamls
    repoURL: https://github.com/taer/argo-rollout-issue
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
